openapi: 3.0.3
info:
  title: Auth
  version: 1.0.0
paths: {}
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        name:
          type: string
      required: [email, password]
    UserProfile:
      type: object
      properties:
        id:
          type: string
        clerkId:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
      required: [id, clerkId, email]


