openapi: 3.0.3
info:
  title: Auth Paths
  version: 1.0.0
paths:
  /auth/register:
    post:
      tags: [Auth]
      summary: 사용자 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../schemas/auth.yaml#/components/schemas/RegisterRequest"
      responses:
        '201':
          description: 생성됨
          content:
            application/json:
              schema:
                $ref: "../schemas/auth.yaml#/components/schemas/UserProfile"
        '400':
          description: 잘못된 요청
  /auth/profile/{clerkId}:
    get:
      tags: [Auth]
      summary: 사용자 정보 조회
      parameters:
        - in: path
          name: clerkId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: "../schemas/auth.yaml#/components/schemas/UserProfile"
        '404':
          description: 찾을 수 없음
    put:
      tags: [Auth]
      summary: 사용자 정보 업데이트
      parameters:
        - in: path
          name: clerkId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: 업데이트됨
          content:
            application/json:
              schema:
                $ref: "../schemas/auth.yaml#/components/schemas/UserProfile"
        '404':
          description: 찾을 수 없음
    delete:
      tags: [Auth]
      summary: 사용자 삭제
      parameters:
        - in: path
          name: clerkId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 삭제됨
        '404':
          description: 찾을 수 없음


