openapi: 3.0.3
info:
  title: Doctors Paths
  version: 1.0.0
paths:
  /doctors:
    post:
      tags: [Doctors]
      summary: 의사 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 의사 이름
                email:
                  type: string
                  format: email
                  description: 의사 이메일
                phone:
                  type: string
                  description: 의사 전화번호
                speciality:
                  type: string
                  description: 의사 전문과목
                bio:
                  type: string
                  description: 의사 소개
                imageUrl:
                  type: string
                  description: 의사 이미지 URL
                gender:
                  type: string
                  enum: [MALE, FEMALE]
                  description: 의사 성별
              required:
                - name
                - email
                - phone
                - speciality
                - imageUrl
                - gender
      responses:
        201:
          description: 의사 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: 의사 생성 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []
  /doctors/active:
    get:
      tags: [Doctors]
      summary: 모든 활성 의사 조회
      responses:
        200:
          description: 모든 활성 의사 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: 모든 활성 의사 조회 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []
  /doctors/{id}:
    get:
      tags: [Doctors]
      summary: ID로 의사 조회
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: ID로 의사 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: ID로 의사 조회 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []
    put:
      tags: [Doctors]
      summary: 의사 정보 업데이트
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 의사 이름
                email:
                  type: string
                  format: email
                  description: 의사 이메일
                phone:
                  type: string
                  description: 의사 전화번호
                speciality:
                  type: string
                  description: 의사 전문과목
                bio:
                  type: string
                  description: 의사 소개
                imageUrl:
                  type: string
                  description: 의사 이미지 URL
                gender:
                  type: string
                  enum: [MALE, FEMALE]
                  description: 의사 성별
                isActive:
                  type: boolean
                  description: 의사 활성 여부
      responses:
        200:
          description: 의사 정보 업데이트 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: 의사 정보 업데이트 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []
    delete:
      tags: [Doctors]
      summary: 의사 삭제
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        200:
          description: 의사 삭제 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: 의사 삭제 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []
  /doctors/speciality/{speciality}:
    get:
      tags: [Doctors]
      summary: 전문과목으로 의사 조회
      parameters:
        - in: path
          name: speciality
          required: true
          schema:
            type: string
      responses:
        200:
          description: 전문과목으로 의사 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: 전문과목으로 의사 조회 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []    
  /doctors/{doctorId}:
    get:
      tags: [Doctors]
      summary: 의사의 예약 목록 조회
      parameters:
        - in: path
          name: doctorId
          required: true
          schema:
            type: string
      responses:
        200:
          description: 의사의 예약 목록 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        400:
          description: 의사의 예약 목록 조회 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - BearerAuth: []
